### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by objestik** [Kaplas80/TranslationFramework2#1]

**Comment by Kaplas80** [comment]
You can compile it using Visual Studio 2019 Community.

**Comment by NoobieAraby** [comment]
Newbie here, I can't seem to work that out

**Comment by Kaplas80** [comment]
Well, I can't help you if I don't know the details. What error does appear when you try to compile the code?

**Comment by objestik** [comment]
![Capture](https://user-images.githubusercontent.com/28157614/57638672-90772f00-75ae-11e9-86b2-20c28f5b091c.PNG)

**Comment by Kaplas80** [comment]
You are trying to run one of the plugins. You have to select TF.GUI as startup project.

https://blogs.msdn.microsoft.com/zainnab/2010/05/09/choosing-the-startup-project/

**Comment by objestik** [comment]
![Capture](https://user-images.githubusercontent.com/28157614/57642008-ab4da180-75b6-11e9-9437-0e98264ec0e8.PNG)

**Comment by objestik** [comment]
what about this last problem?

**Comment by Kaplas80** [comment]
That error means that compilation failed and .exe was not generated. There should be a list of compilation errors on "Output" tab.

Probably, nuget didn't download the project references. You have to enable the "automatic download" option: https://docs.microsoft.com/es-es/nuget/consume-packages/media/restore-01-autorestoreoptions.png

**Comment by objestik** [comment]
![Capture](https://user-images.githubusercontent.com/28157614/57657090-91be5100-75da-11e9-8f62-a5b7698c61ef.PNG)
This is the error I'm getting.
I've checked with the nuget, it's checked like in the pic you linked.

**Comment by Kaplas80** [comment]
Well, for the resx error, just replace "Mayús." with "Shift" in line 356.

To fix the "WeifenLuo" warnings, open the nuget package manager ("Tools" menu -> "NuGet package manager" -> "Manage NuGet packages...") and make sure that "Include preliminary version" option is checked:

![Sin título](https://user-images.githubusercontent.com/5345429/57659128-7b67c380-75e1-11e9-8c36-043ad6c58b0a.png)

**Comment by objestik** [comment]
dang, it wont work even when I changed that Mayus to Shift.

**Comment by Kaplas80** [comment]
What is the error message now?

**Comment by objestik** [comment]
![Capture](https://user-images.githubusercontent.com/28157614/57666129-29359b00-75ff-11e9-8d42-ecc12832878c.PNG)

**Comment by Kaplas80** [comment]
You have to remove the dot in "Shift."

<value>Ctrl+Shift+F</value>

**Comment by objestik** [comment]
Worked, thanks and sorry for the trouble  :)
![Capture](https://user-images.githubusercontent.com/28157614/57791282-c2b69700-773c-11e9-8553-fe714fdbbece.PNG)

**Comment by Kaplas80** [comment]
Great! I'm closing the issue, if you have any other problem, reopen it.

**Comment by objestik** [comment]
![photo_2019-05-19_04-00-13](https://user-images.githubusercontent.com/28157614/58027125-3c24ff80-7b18-11e9-9afa-874287bcbbbf.jpg)
I'm having a trouble browsing Yakuza 0 game data using the tool. I can't seem to open ui_e.par files.

**Comment by Kaplas80** [comment]
It works here.
![Sin título](https://user-images.githubusercontent.com/5345429/58034325-a644a100-7b26-11e9-8d2d-911ad49fd0ac.png)

It's easier if you fork the project in github and upload your changes, then I could see your code and try to find the bug.

**Comment by objestik** [comment]
Alright, I'll check that out again and I let you know

**Comment by objestik** [comment]
I forked it and changed the code so I can try and translate some of the games to Arabic.

**Comment by Kaplas80** [comment]
Well, there is a problem with DirectXTexNet nuget reference. You have to open nuget package manager in TF.Core project, remove that reference and add it again. Then recompile solution and create a new translation.

**Comment by objestik** [comment]
![Capture](https://user-images.githubusercontent.com/28157614/58851298-6cc97500-8692-11e9-9703-fcf2752aa634.PNG)
I've tried that. Deleting DirectXTexNet in TF.Core, and reinstalling it. Still can't view the game's files and having this (?) icon like in the picture attached.

**Comment by Kaplas80** [comment]
Have you fixed the bug in Encoding.cs?

https://github.com/objestik/TranslationFramework2/commit/2e34058cfea1333c751c3fa595d5593677078add

**Comment by objestik** [comment]
Nope, wait
I'll try that out

**Comment by objestik** [comment]
It finally worked!... but

**Comment by objestik** [comment]
![Capture](https://user-images.githubusercontent.com/28157614/58985971-bd4ce980-87dc-11e9-8957-5dd9b3b81c7b.PNG)
I'm having this error every time I open up 

> media.\Yakuza0.exe

**Comment by Kaplas80** [comment]
That error usually happens when you are trying to translate a old version of the game. The app only works with the latest game version (v4, released on 2019/03/26)

**Comment by objestik** [comment]
Jesus installed the latest version, and it worked

**Comment by objestik** [comment]
thank you

**Comment by objestik** [comment]
![Capture](https://user-images.githubusercontent.com/28157614/59557343-cbb6b480-8fd7-11e9-89ed-7590e5b2d397.PNG)

**Comment by objestik** [comment]
If you could upload the tool compiled and ready to use I'd appreciate it

**Comment by Kaplas80** [comment]
Hi! The compiled files are in this folder: https://mega.nz/#F!GZNQWSBQ!JA42-HIGTy79O0I7is0FGw

**Comment by sirargo** [comment]
hello, I'm italian, sorry for my bad english. The compiled is olnly for translate in spanish, please send me istruction to traslate from english to italian. Thank you

**Comment by Kaplas80** [comment]
Hello! The application is in Spanish, but you can use it to translate the games to Italian.

Please, if you have other problems or questions, open a new issue to keep threads clean.

**Comment by sirargo** [comment]
on zenhax I read what is reported below, that's why I asked you the procedure to make it become Italian. Thank you

"The app has been created to translate the games from English to Spanish. If you need to translate them from/to other languages, I can help you explaining the file formats or how the app work, but you'll have to make the necessary code changes. I'm sorry if this sounds a bit rude, but my time is limited and I prefer to spend it investigating how to translate other games than patching the app to translate to other languages."
