### ISSUE TITLE
Cyrillic

### ISSUE THREAD

**Issue by JackMonores** [Kaplas80/TranslationFramework2#10]
Good afternoon! Can I use Cyrillic for translation in the program? In my game, the text is out of bounds and the font is very large.
![Снимок](https://user-images.githubusercontent.com/57320181/74709278-5def1680-5251-11ea-80ee-102c0662db38.PNG)

**Comment by Kaplas80** [comment]
Hi! In Yakuza games, the cyrillic font have "fixed width".

To adjust the width, you can try to replace the characters in the occidental font (hd_hankaku.dds) with cyrillic ones but, in that case, you'd have to modify and recompile my app (file Encoding.cs) to make the characters substitutions in game files.

**Comment by JackMonores** [comment]
This file needs to be edited in Kiwami or Zero version and what exactly will need to be changed? I only recently started doing this, and I apologize for such stupid questions.
![Снимок](https://user-images.githubusercontent.com/57320181/74724374-bda7ea80-526e-11ea-9cca-ca26166440d1.PNG)

**Comment by Kaplas80** [comment]
Hi. You have to modify `EncodingReplacements` list, adding the characters you want to replace. You have to add one tuple for each replaced character, the first item in the tuple is the cyrillic char and the second one is the original char.

If you are translating Yakuza Kiwami, you have to modify Kiwami's `Encoding.cs`

**Comment by JackMonores** [comment]
> Hi. You have to modify EncodingReplacements
I have to modify it in Encoding.cs? If so, can you tell us exactly where and how?(if you wish)

**Comment by Kaplas80** [comment]
Yes, it starts in line 24 of `Encoding.cs`

```csharp
            EncodingReplacements = new List<Tuple<string, string>>
            {
                new Tuple<string, string>("\\r", "\r"),
                new Tuple<string, string>("\\n", "\n"),
                //new Tuple<string, string>("®", "\u007F"),
                new Tuple<string, string>("¥", "\\"),
            };
````
You have to add one tuple for each char you want to replace. For example, if you replace `A` with `Д` in the .dds image, you have to modify `EncodingReplacements` this way:

```csharp
            EncodingReplacements = new List<Tuple<string, string>>
            {
                new Tuple<string, string>("\\r", "\r"),
                new Tuple<string, string>("\\n", "\n"),
                //new Tuple<string, string>("®", "\u007F"),
                new Tuple<string, string>("¥", "\\"),
                new Tuple<string, string>("Д", "A"),
            };
```

**Comment by JackMonores** [comment]
Thanks, I'll try

**Comment by Giza** [comment]
> (I translate Kiwami
Liar. Врет и не краснеет. Мимокрокодил

**Comment by JackMonores** [comment]
Liar. Врет и не краснеет. Мимокрокодил
Ахаха, приятно видеть своих, но я этим занимаюсь лишь для себя)

**Comment by Kaplas80** [comment]
Please, keep your discussions out of here.
