### ISSUE TITLE
Yakuza Kiwami bug tutorial

### ISSUE THREAD

**Issue by linkmadao** [Kaplas80/TranslationFramework2#11]
After translating the tutorial, the heat button doesn't work. All other items in the battle work, only the heat action attack does not, the life bar apparently gets lower too. 
I've tried to replace all files with the originals and try again after the save corrupts, but it doesn't work. The only thing that really worked was doing the tutorial and then adding the translation.

With bug:
https://cdn.discordapp.com/attachments/616048790113222729/671775774034100224/unknown.png

Without bug:
https://cdn.discordapp.com/attachments/616048790113222729/671776419168387072/unknown.png

The translation kind of corrupts the save, blocking the game's internal functions, for example, that of HP, it is as if it had its stamina/life/blows reset. Something interfered with that.
The difference, the button appears to use the HEAT ACTION ATTACK

**Comment by Kaplas80** [comment]
Hi!
I don't have that bug report from spanish translator, and I'm pretty sure that he has translated the tutorial.

That kind of bug seems to be because you tried to translate some text that the game doesn't "allow" to translate. Some texts (usually the fighting styles) in some files breaks the game if you change them.

I'll ask the spanish translator in case he has got the same error.

**Comment by linkmadao** [comment]
Do you have the contact ?

Atenciosamente,
Tiago Silva Miguel
Técnico em informática / Programador C#
I.T. / C# Programmer
+55 31 99466-7444
________________________________
De: Kaplas80 <notifications@github.com>
Enviado: Tuesday, February 18, 2020 9:16:47 AM
Para: Kaplas80/TranslationFramework2 <TranslationFramework2@noreply.github.com>
Cc: Tiago Silva Miguel <tiagos.miguel@outlook.com>; Author <author@noreply.github.com>
Assunto: Re: [Kaplas80/TranslationFramework2] Yakuza Kiwami bug tutorial (#11)


Hi!
I don't have that bug report from spanish translator, and I'm pretty sure that he has translated the tutorial.

That kind of bug seems to be because you tried to translate some text that the game doesn't "allow" to translate. Some texts (usually the fighting styles) in some files breaks the game if you change them.

I'll ask the spanish translator in case he has got the same error.

**Comment by Giza** [comment]
There are many names that cannot be translated. System names
