### ISSUE TITLE
Yakuza Kiwami: file ai_popup.bin is not saved correct.

### ISSUE THREAD

**Issue by Giza** [Kaplas80/TranslationFramework2#13]
File media\data\wdr_par_c\common.par\ai_popup.bin after the change, it is not saved correctly. And when trying to open it, an error occurred.

**Comment by Kaplas80** [comment]
Hi!

Thanks for finding the bug, it should be fixed now. Please, update the app and let me know if it works.

**Comment by Giza** [comment]
It works. Thx
