### ISSUE TITLE
Yakuza Kiwami: not all texts are available

### ISSUE THREAD

**Issue by Giza** [Kaplas80/TranslationFramework2#14]
Ex: no unpacks files in folder media\data\scenario\
not all text in EXE. ex text: "Select the display on which to render the game"

**Comment by Kaplas80** [comment]
Hi!

I've added the `scenario2` files to the app, but I'm not sure if they are translatable. They have a lot of texts in Japanese and only a few in English. Also, `scenario2.bin_c` ends in a invalid encoded string.

Anyway, I can't test them in-game so, please, let me know if it works.

About the exe file, I've added the text you mention. But, as I have to add the texts manually, it is very possible that there are other missing texts.

**Comment by Giza** [comment]
scenario2.bin_c incorrect export. Eng text "October 1, 1995"
![image](https://user-images.githubusercontent.com/1367250/79845946-c5177b80-83f8-11ea-98c1-be76dcaa53d7.png)
That is, the hex of the text starts in a different place. If you can't do it, just forget it. I'll do it manually.

EXE: more texts: start adress
CA5AB8
CA5B38
CA5C18
CA1DD8

**Comment by Kaplas80** [comment]
About the incorrect export, I've noticed and fixed it a few minutes about 20 minutes ago. Please, update the app and test it again.

I'll add the exe texts later.

**Comment by Giza** [comment]
Thx. I'll wait for the new build in mega for test. Seem to have forgotten to upload

**Comment by Kaplas80** [comment]
I've just updated the app to add the missing exe texts.

I'm sorry, but I can't add the text starting at 0xCA5C18 because it isn't referenced inside the exe file (or, at least, it isn't referenced like the other texts). If you want to modify it, you'll have to do it with an hex editor.

**Comment by Giza** [comment]
Oh. Thank you again. No more questions yet
