### ISSUE TITLE
Love Esquire

### ISSUE THREAD

**Issue by foubou** [Kaplas80/TranslationFramework2#15]
Is TranslationFramework working with version 1.2.9 of Love Esquire (just bought it on Steam) or it works only with 1.2.4 as mentioned in TF2 when opening a new project ?
It is also said that vntext.sq and Assembly-CSharp.dll must be modified but how ? I mean what are the changes I should do to these files ?
Thank you Kaplas, I am really enjoying your soft !

**Comment by Kaplas80** [comment]
Hello!
I don't think it will work with v.1.2.9, but you can try.

The patch in Assembly-CSharp.dll is no longer necessary and, for vntext.sq, you can use this one: https://mega.nz/folder/OJlyRC6Q#GWMTu05pXZmFcjmJSjnR8A

Or you can try to patch it yourself with this tool: https://github.com/Kaplas80/TranslationFramework2/tree/master/src/ExternalTools/LoveEsquireVnTextBuilder

**Comment by foubou** [comment]
Thank you, I tried that but unfortunately, it didnt work. I dont think it works with version 1.2.9 toi.
![error text 1](https://user-images.githubusercontent.com/26176310/92036198-24ef3d00-ed70-11ea-933c-ff1568ad63d3.png)
![error text 2](https://user-images.githubusercontent.com/26176310/92036266-3f291b00-ed70-11ea-917c-7c2b5bd6aca9.png)
![error text 3](https://user-images.githubusercontent.com/26176310/92036312-4bad7380-ed70-11ea-8688-3cb5df28d1d1.png)
![error text 4](https://user-images.githubusercontent.com/26176310/92036338-55cf7200-ed70-11ea-8443-3c3b644b432a.png)
