### ISSUE TITLE
How to download ?

### ISSUE THREAD

**Issue by o6498** [Kaplas80/TranslationFramework2#16]
Hi, I'm trying to download the file using the link you provided but it's stuck in infinite loading with mega, is there any fix ? thank you !

![image](https://user-images.githubusercontent.com/70380168/91658758-5abfc780-eacb-11ea-9920-4f0f138651ad.png)

**Comment by Kaplas80** [comment]
Hello!

I've tested the link and it works well. Try with other browser.
