### ISSUE TITLE
traslate to italian

### ISSUE THREAD

**Issue by sirargo** [Kaplas80/TranslationFramework2#17]
I have use the application but i no have found the selection of language during the process, How to select italian language for exported text? thankyou

**Comment by Kaplas80** [comment]
You don't need to select the language. The application just replaces the English texts with the ones you write.

**Comment by sirargo** [comment]
I understand, but how can I choose IT, Italian? I did the procedure, but it never made me choose the Italian language, do I have to edit some files after export? Sorry to bother you :(

**Comment by Kaplas80** [comment]
I don't understand... Where do you want to choose italian language?

The app don't "know" to what language is making the translation, it just replaces the texts.

**Comment by sirargo** [comment]
on zenhax I read what is reported below, that's why I asked you the procedure to make it become Italian. Thank you

"The app has been created to translate the games from English to Spanish. If you need to translate them from/to other languages, I can help you explaining the file formats or how the app work, but you'll have to make the necessary code changes. I'm sorry if this sounds a bit rude, but my time is limited and I prefer to spend it investigating how to translate other games than patching the app to translate to other languages."

**Comment by Kaplas80** [comment]
I wrote that because there are many languages that use a different character set, but I don't think Italian is one of them.

I suppose that you want to translate one of the Yakuza games, so, if you'd need to add a special character that is not included in the spanish font, you'd have to replace one of the existing in the font image (the .dds file) and modify the class `Encoding` in the app code so it is aware of the replacement.

**Comment by sirargo** [comment]
I understood. Thanks to the application I was able to extract several .po files with internal text that I will have to translate into Italian. If I can translate all these files, then how can I copy them into the game? I followed the "MAXIMO" procedure followed by "TEXTOS" and then "EXPORTAR". Once all the .PO files have been translated, how do I insert them into the game to make the Italian language appear? Thank you

**Comment by Kaplas80** [comment]
Once you have translated the .po files, you can load them into the application using "Masivo" - "Textos" - "Importar" to import all of them at once, or do it one by one using the button that is located at the bottom of the app main window when you are viewing each one of the files in the app.

After that, you have to press "Archivo" - "Exportar..." and it will create the translated game files.

Finally, replace the original game files with the new ones and run the game.
