### ISSUE TITLE
Yakuza Kiwami 2

### ISSUE THREAD

**Issue by MechaPoulpe** [Kaplas80/TranslationFramework2#18]
Hi ! 
First, thank you a lot for you amazing work. I manage to translate Yakuza kiwami 1 to french with your tool (next one is Yakuza 0).

I was wondering if your branch Yakuza kiwami 2 is still up-to-date ? I download it and run it, but it was impossible to open a .bin file.

Hope you did not stop your great works, you are the only one who do this kinds of this for Yakuza (SEGA MUST HIRE YOU!)

**Comment by Kaplas80** [comment]
Hello!

Thank you very much for your words, I'm glad to know that the application is useful for translating into different languages.

Answering your question, that branch is not functional, but I'm working to make Kiwami 2 the first translatable game with the future v3 of the application (too soon to set a release date).

If you want to read and write .bin files, you can use [reARMP](https://github.com/CapitanRetraso/reARMP), which converts them to JSON (although I don't think the format is confortable to do a translation).

Regards.

**Comment by MechaPoulpe** [comment]
Hi! Thanks you for your quick response!
I'll be very happy to test/use the V3 of your app, is it possible to include a mechanism to be able to switch language (of the app) ?

If that's the case, I'll be happy to do a french translation of it, also I can do some kind of beta testing if you want.

**Comment by Kaplas80** [comment]
Thank you, I'll let you know if I need help with app translation or testing.

**Comment by foubou** [comment]
@MechaPoulpe : Salut, super de voir un autre francophone. Moi aussi, je traduis des jeux, et je veux bien t'aider à traduire en français le logiciel. Tu te concentres exclusivement sur les Yakuza ?

@Kaplas80 : Thank you for your work and your amzing sofware !

![TF2 in french](https://user-images.githubusercontent.com/26176310/100755782-d6901f80-33ec-11eb-885b-7d4aa22e8840.png)

**Comment by MechaPoulpe** [comment]
@foubou Salut salut, effectivement je ne me concentre que sur la série des Yakuza pour l'instant. J'avais aussi modifié l'interface de l'application directement en modifiant le code source mais il serait mieux d'implémenter un système d'internationalisation directement au sein de l'application
