### ISSUE TITLE
English to UTF8

### ISSUE THREAD

**Issue by toimuonthunghiem** [Kaplas80/TranslationFramework2#2]
Hello Kaplas80, thank you so much for creating such an excellent framework.

I don't know how to contact you beside submit new issues through Github, sorry if I'm bothering you.

This is my first time trying to translate Yakuza 0 to Vietnamese (or I could say first time trying to translate a game), so I don't know how to make the text to Vietnamese Character.

I have the .dds file that you included now, so what next step I need to do so the game can read our language character? Thank you.

![vietnamese_character_list](https://user-images.githubusercontent.com/52458826/60757008-ff14be00-a02e-11e9-820a-933d0743f2d8.png)

**Comment by Kaplas80** [comment]
I'm glad you got it sorted out. If you have any other questions, open another issue.

PS. There is a user (minhr883) on the zenhax forums who was also translating the game into Vietnamese.
