### ISSUE TITLE
Font for Yakuza 0

### ISSUE THREAD

**Issue by mildlyfrosting** [Kaplas80/TranslationFramework2#20]
I use this program to translate Yakuza 0 to Thai language. But when I applied to the game. I cannot see the alphabet in game. I think it's bc Thai language not use any English alphabet. So, I tried to change the font. I already use Gibbed to unpack 'font.par' and it has .dds font file in 'font.par'. But I have only .ttf font file. So, I tried to use .ttf converter to .dds. But still can't use the font. Do you have any idea how to make .dds file font. Or how to solve this problem. Please help me. tysm

PS1. I came to ask in github bc I cant create zenhax account. Sorry.
PS2. I don't have experience in making any mod T.T

**Comment by Kaplas80** [comment]
Hello!

There is no need to use Gibbed tool. These are the steps to change the font in game:

1. Open the translation project in the app and select `hd_hankaku.dds` inside `font.par`.
2. Press `Exportar` and save the file where you want.
3. Edit the dds using Photoshop, GIMP, Paint.NET or other DDS image editor, replacing the existing characters with the ones you need.
4. In TranslationFramework, press `Importar` and select the DDS with the new characters.
5. In TranslationFramework, select `Yakuza0.exe` inside `media`.
6. Select `Parches` tab and check `Usar codificación ISO-8895-1`.
7. Select `Fuente` tab, press `Cargar Fuente Nueva` button, and select again your DDS file.
8. Press `Auto Ajustar` to adjust the character spacing in game (you can adjust manually using the numeric table, but it is easier to do it with `Auto Ajustar`).

**Comment by mildlyfrosting** [comment]
Oh, I will try all this step. Thank you so much.

But I have problem when I click on hd_hankaku.dds
It appear like this
![image](https://user-images.githubusercontent.com/77139515/104030464-06a5bc00-51fe-11eb-804d-d3145664c408.png)

**Comment by Kaplas80** [comment]
It could be because the files in `x86` and `x64` subdirectories inside the app directory are blocked. Try to unblock using this guide: https://www.msftnext.com/how-to-unblock-files-downloaded-from-internet-in-windows-10/

**Comment by mildlyfrosting** [comment]
Thank you again! I can export hd_hankaku.dds now. I decide to use GIMP. But I think I can't replacing alphabet in my language bc it's really different... and it has more than 50 characters. *crying*

So, I think I will make new file for this font. What I want to know is after I type all character in GIMP like this. So I can save it as .dss then it's done or do I need to anything to make it can read all this character.
![image](https://user-images.githubusercontent.com/77139515/104041648-f5fc4280-520b-11eb-9a02-0f4e7fd62141.png)

**Comment by Kaplas80** [comment]
You can't do that: the size and position of each character inside the image are important.

I think you'll have to draw each character using [ISO-8859-11](https://en.wikipedia.org/wiki/ISO/IEC_8859-11#Character_set) order. Then, you'll have to modify [this line](https://github.com/Kaplas80/TranslationFramework2/blob/a4ad74add15235f2e224ce7a4daa81b8ec371ff0/src/Plugins/TFGame.Yakuza0/Encoding.cs#L11) of the app to make it use that encoding.

If you are lucky, those changes would be enough to translate the game, but I think you'll also have to find a way to patch the exe file to allow the game to use all the Thai characters.

**Comment by mildlyfrosting** [comment]
I already type all character in GIMP. And compared the size to original file. So, I got this. 
So, I can save the file now. right? Or I made a mistake again T_T
![image](https://user-images.githubusercontent.com/77139515/104084618-524a7b00-527b-11eb-905b-5d2ff3b344a0.png)

You said that I need to modify 'this line'. But I don't have Encoding.cs
I download program from [this link](https://mega.nz/#F!GZNQWSBQ!JA42-HIGTy79O0I7is0FGw)

**Comment by mildlyfrosting** [comment]
Oh. I have another idea right now. I will use the old .dds file. And replace character that I want like you told at the first. But it will be a little confuse for me. I will try to use encoder/decoder program to type text. I will try this method while you not online. Bc our time zone is so much different... I will update about this soon.

**Comment by Kaplas80** [comment]
Hi!

You have to put each character replacing other character in the original dds, __the position inside the image is important__.

The app you downloaded is made for translating the game to Spanish and other latin languages, so it uses ISO-8859-1 encoding. If you don't change the line I told you in the last message, it will be harder to translate to your language, because you'll have to insert latin characters to make the game show thai characters.

Example: if you don't change the encoding, to make the game show `ม`, you'll have to write `Á` in the application.

And, probably, that change won't be enough to translate the game, so my advise is that you contact some developer that can help you to adapt the app to your needs (that is the reason why I made it open source).

About your idea of using images to make subtitles, that is not possible. The game use texts for the subtitles and you can't change that.

**Comment by mildlyfrosting** [comment]
This is why I'll just use the old file.. I'm ok to type latin and use encoder/decoder program to help.
> And, probably, that change won't be enough to translate the game, so my advise is that you contact some developer that can help you to adapt the app to your needs (that is the reason why I made it open source).

I contact many mod maker in my country. Some don't know anything about this, and some of them just give up on this. This problem happens in RE1 too. They try many things but Thai language is such a mess and they give up :(

But I don't want to. Then I think I'm ok to type in Latin T_T

Now, I have new problem.. I don't know why I can't import font file even original file from game.
It happens like this too. I try to start new entire project and redownload yakuza 0. I think problem is from my file.
> ![image](https://user-images.githubusercontent.com/77139515/104087370-cdb72700-5291-11eb-84d0-057d24fd827d.png)

I'll update soon

**Comment by mildlyfrosting** [comment]
I already redownload game and start new project.
I try to export hd_hankaku.dds and click on 'cargar fuente nueva' and select original file that I just export.
Still appear like this...
![image](https://user-images.githubusercontent.com/77139515/104089546-900eca00-52a2-11eb-8572-42985a498da9.png)

**Comment by mildlyfrosting** [comment]
I redownload the game and start new entire project again.
I export 'hd_hankaku.dss' then click on 'cargar fuente nueva' and click on original file that I just export.
But still appear like this
![image](https://user-images.githubusercontent.com/77139515/104089631-014e7d00-52a3-11eb-960b-9012a202be81.png)

**Comment by Kaplas80** [comment]
Thank you for finding that bug. I've fixed it and uploaded a new version of the app.

**Comment by mildlyfrosting** [comment]
I try to applied font. But when I open game it appear like this...
![image](https://user-images.githubusercontent.com/77139515/104103337-1db6dd80-52d4-11eb-8b84-1230c55152b5.png)

But when I test in in program it's fine
![image](https://user-images.githubusercontent.com/77139515/104103381-640c3c80-52d4-11eb-983a-e98b9f29f7ae.png)

**Comment by Kaplas80** [comment]
I think that you are not using the same dds in the exe file (to set the character spacing) and the one inside `font.par`.

**Comment by mildlyfrosting** [comment]
I use same dds but still like this... I didn't change anything in English part. I replace just Latin part.
![image](https://user-images.githubusercontent.com/77139515/104182560-3b568500-5443-11eb-8b1f-12700a13573e.png)

**Comment by mildlyfrosting** [comment]
Update again!!! Finally!!! I can translate to Thai.
![image](https://user-images.githubusercontent.com/77139515/104186095-7909dc80-5448-11eb-905c-cdb5123fe8d5.png)
Thank you so much for all 3 days. I'm asking so many question.
You can close my issue <3 <3

**Comment by Kaplas80** [comment]
Great! Let me know if you find other bugs.
