### ISSUE TITLE
Texts not found - Yakuza Kiwami

### ISSUE THREAD

**Issue by linkmadao** [Kaplas80/TranslationFramework2#22]
Looking deeper into our project, I couldn't find the following words to translate.

Text: Enabled 
Screen: Settings -> Graphics
Item: v-sync
![image](https://user-images.githubusercontent.com/6817344/107150981-1b7d8880-693f-11eb-99b8-e183362168c9.png)

Text: Off
Screen: Settings -> Graphics -> Advanced 
Item: render scale
![image](https://user-images.githubusercontent.com/6817344/107151116-ae1e2780-693f-11eb-8325-7c84a81ea09f.png)

Text: Off
Screen: Settings
Item: hide interface
![image](https://user-images.githubusercontent.com/6817344/107151041-541d6200-693f-11eb-9449-4d42ffe03fcd.png)

Text: Off
Screen: Settings -> Remap buttons controller
Item: hide interface
![image](https://user-images.githubusercontent.com/6817344/107151179-fb9a9480-693f-11eb-9213-1ebfefed0e33.png)

Text: Autosave
Screen: Continue
![image](https://user-images.githubusercontent.com/6817344/107151380-0d306c00-6941-11eb-9887-fcd4b24a2722.png)

**Comment by Kaplas80** [comment]
Hello!

I don't remember those specific strings, but maybe I left them out because they broke the game when translated.

Anyway, you can search them inside the exe with an hex viewer and if you find them, you can add their offsets to [AllowedStringOffsets](https://github.com/Kaplas80/TranslationFramework2/blob/d2039dba151b02233688a7c8695cd1bc6a113e88/src/Plugins/TFGame.YakuzaKiwami/Files/Exe/File.cs#L15) list to make the app show them for translation.

**Comment by linkmadao** [comment]
I'm putting this way, is correct?
![image](https://user-images.githubusercontent.com/6817344/107155379-cc435200-6956-11eb-9cca-8b0cbc8689a6.png)

![image](https://user-images.githubusercontent.com/6817344/107155374-c3528080-6956-11eb-9820-a24fc9523ca8.png)

**Comment by Kaplas80** [comment]
No, that is the translated exe. You have to use the string offset from the original exe.

But... If `Autosave` is there, it means that my app has already found it and you should be able to translate it.

**Comment by linkmadao** [comment]
You didn't understand what i've sayed kkkk. I'm just ask if the method i used on Tuple is right.

**Comment by Kaplas80** [comment]
The strings are stored in groups inside the exe. You have to write the offset of the first string at the first item of the tuple and the offset of the last string at the second item. As an example:

![image](https://user-images.githubusercontent.com/5345429/107489284-bb7a2280-6b88-11eb-8184-abfb4b0a7141.png)

That is a group of 2 strings: `Autosave Complete` is the first string and it starts at offset `0x00CA5B38` and `Autosave` is the last string and it starts at offset `0x00CA5B50`

So, in the code there is the tuple: `new Tuple<long, long>(0x00CA5B38, 0x00CA5B50),`

![image](https://user-images.githubusercontent.com/5345429/107489125-8bcb1a80-6b88-11eb-9472-f74c19d1300e.png)

And you have to keep in mind that the application will only translate strings that are located in the `.rdata` section and are referenced in the `.data` section. Any other string will be ignored even if you write a tuple for it.

**Comment by Kaplas80** [comment]
Hi!

Were you able to find and add more texts to translate?

**Comment by linkmadao** [comment]
No, I haven't had time yet to look again at the missing texts.

But we can close this topic, because I already understood how it should be done.
