### ISSUE TITLE
Can you tell me which folder I should choose and which program I should choose?

### ISSUE THREAD

**Issue by shun9092** [Kaplas80/TranslationFramework2#24]
[https://imgur.com/YFVLSJU](https://imgur.com/YFVLSJU)

About Yakuza Itshin!
I have to choose two routes below, but I don't know Spanish so I don't know which one to choose.
Can you tell me which folder I should choose and which program I should choose?

**Comment by Kaplas80** [comment]
Hello!

The first one is the "working folder": you have to select an empty directory where the app will write extracted files, temporary files and other stuff.

The second one is the "installation folder": you have to select the directory where the game files are. For Yakuza Ishin, it is the "USRDIR" folder.

**Comment by shun9092** [comment]
Thank you for your quick response.

Can you support English other than Spanish?

I can't understand because it's Spanish.

**Comment by shun9092** [comment]
[https://imgur.com/begsMVL](https://imgur.com/begsMVL)

Is that it?

How do I modify the game in this program?

**Comment by Kaplas80** [comment]
Hi again!

> Can you support English other than Spanish?

No, sorry. The [future app](https://github.com/Kaplas80/TF3) will be in English (or multilanguage, I haven't decided yet), but this one will remain in Spanish. And I don't know if I'll migrate the games from this app to the new one.

> Is that it?

Yes, that's ok. Now, at the left side of the app, you'll have a file tree. Select the file you want to edit, translate the texts and, when you have finished, click on the menu "Archivo - Exportar", select the files you want to rebuild and you'll find them in the "export" directory inside the working folder.

> It it possible to create a Font?

No, sorry again. Yakuza Ishin support is only partial. With this app you only can translate text files (and, probably, there are texts in other files that the app doesn't recognize), but you can't create/replace fonts or images.

**Comment by shun9092** [comment]
[https://imgur.com/oFkYXNz](https://imgur.com/oFkYXNz)

What is right's options?

Can you explain to me?

Sorry, becouse I don't know Spanish...

**Comment by Kaplas80** [comment]
That options are mainly for debuging, so you probably haven't to change it:

- "Comprimir" (Compress): In some games you can choose to compress the new files or leave them uncompressed, so the creation is faster.
- "Forzar creación" (Force creation): By default, if a file hasn't changed, the app just copy the original. Enabling this option, the app will process it as if it had changed.
- "Guardar ficheros temporales" (Save temporary files): By default, the app deletes the temp files that it needs for processing. Enabling this option will keep it in the "temp" folder of the working directory.

If you don't understand Spanish, I recommend you to use a mobile phone camera to translate the app texts in "real time" most of them are short texts and the google translator will manage them without problem. Of course, if after using it, you still don't understand what it means, you can ask me here.

**Comment by shun9092** [comment]
[https://imgur.com/YFVLSJU](https://imgur.com/YFVLSJU)

For the Yakuza series steam version, which folder should I select?

**Comment by Kaplas80** [comment]
In both cases, you have to choose the directory where the "media" directory is located:

![image](https://user-images.githubusercontent.com/5345429/109385704-1edcb200-78f6-11eb-8271-3991d19f6764.png)
