### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by amrshaheen61** [Kaplas80/TranslationFramework2#26]
How I can fix this bug
![Annotation 2021-03-11 040119](https://user-images.githubusercontent.com/65582303/110724646-da6ae380-821e-11eb-9706-922b752a5f17.png)

**Comment by Kaplas80** [comment]
Hello!

I can't be sure just seeing a screen capture, but I think that you have an old version of the game or the Yakuza0.exe is corrupt. In any case, you can verify the game files with Steam to make sure that they are correct and try to create a new translation project.

**Comment by amrshaheen61** [comment]
@Kaplas80 
Ok I will try again in another version

**Comment by Kaplas80** [comment]
I'm closing this issue. If the problem persists, please let me know and I'll reopen it.
