### ISSUE TITLE
¿Soporte Yakuza 0 (PS3)?

### ISSUE THREAD

**Issue by rocknard** [Kaplas80/TranslationFramework2#28]
Hola, Kaplas. Gracias por esta aplicación.

Entiendo que está hecho para PC, y lo he probado por encima y sí que me muestra los archivos (en japonés). Obviamente, alguna carpetilla tiene otro nombre y el programa te salta algún error de no encontrado (no le he puesto la carpeta del juego de ps3 entera, ya que lo estaba probando).

La pregunta sería: ¿hay alguna pequeña posibilidad de añadir soporte para PS3? Los archivos son casi los mismos (creo que puede haber algún archivo más o menos, pero podría hacerte una lista con todos los archivos), excepto el EBOOT.BIN, *.self y *.sprx (solo hay 1 de cada y se puede desencriptar fácilmente) y el cambio de alguna carpeta:

auth_w64_e > auth 
map_par_e > map_par
motion_64> motion
move_64 > move
pausepar_e > pausepar
wdr_par_c > wdr_par_j

Ya no digo más, que no sé si te interesará.

Nota: me he dado cuenta que el string_tbl.bin_c y el eboot.bin tienen una parte con el mismo código (creo que mencionaste algo de esto de "mirror" en el foro zenhax. Tal vez los cambios deban ser iguales para que todo vaya bien, no?)

**Comment by Kaplas80** [comment]
Hola!

Pues no tenía pensado incluirlo, ya que no tengo ni la consola ni el juego para poder hacer pruebas. Además, tuve que modificar el .exe de PC para que pudiese mostrar las vocales con tilde, la ñ y algunos caracteres más, y supongo que en el de PS3 habría que hacer lo mismo.

De todas formas, si quieres hacer pruebas, en el fichero [Game.cs](https://github.com/Kaplas80/TranslationFramework2/blob/d2039dba151b02233688a7c8695cd1bc6a113e88/src/Plugins/TFGame.Yakuza0/Game.cs) es donde se definen todos los ficheros que tiene que buscar. Por ejemplo, en el método [GetAuth](https://github.com/Kaplas80/TranslationFramework2/blob/d2039dba151b02233688a7c8695cd1bc6a113e88/src/Plugins/TFGame.Yakuza0/Game.cs#L88) es donde le indico que tiene que abrir todos los archivos `.par` de la carpeta `media\data\auth_w64_e` y buscar los ficheros `cmn.bin` y las imágenes dds cuyo nombre empiece por `staffroll` o por `ycap_`.

Después de cambiar los nombres de las carpetas y ficheros, solo tendrías que recompilarlo y probar si funciona.

**Comment by rocknard** [comment]
¿El emulador RPCS3 podría valer para probarlo?

Yo de compilar no tengo indea :). Lo que tal vez sí podría hacer es extraer todos los nombres de archivos y carpetas en un .txt, pero no te quiero meter en el engorro. 

Se me ocurre como "atajo" simplemente desempaquetar todos los archivos con una aplicación que vengo usando y luego cambiar los nombres para que se ajusten a la de PC.

Gracias por la atención Kaplas.

P.S: ¿Sabes dónde se ubica el .dds o archivo del menú donde se encuentra "Inventario, subhistorias, habilidades..."? No me refiero al de "nuevo juego, etc". ¿Me valdría GIMP + dds plugin para editar los dds (¿incluyes la fuente para poner el texto en el dds o es para el texto normal?)?

**Comment by Kaplas80** [comment]
A lo del RPCS3, ni idea. Mi ordenador es demasiado antiguo y la última vez que lo probé con un juego, iba a 1fps.

Lo de desempaquetar los ficheros no te vale, porque mi aplicación espera los ficheros empaquetados. Pero sí que puedes intentar cambiar los nombres de los .par y de las carpetas para que coincidan con los de PC y probar a ver si así funciona.

Y lo del menú, tampoco lo sé. Yo hice la aplicación, pero no la traducción, así que no sé donde está cada cosa.

**Comment by rocknard** [comment]
Ah, vale, entiendo.

Si lo que espera son los .par, entonces no creo que haya problemas, porque en la pequeña prueba que hice ya me mostraba los textos.

Básicamente intentaré usar tu aplicación para comparar tres versiones y ver si todo corresponde y si se muestra igual (en las funciones). Entiendo que podré trabajar con dos "instancias" de la aplicación a la vez, aunque no veo que uno pueda guardar un proyecto para cargarlo más tarde y continuar, ¿no?

Gracias por la atención.

**Comment by Kaplas80** [comment]
Pues no creo que haya ningún problema en abrir la aplicación 2 veces, pero la verdad es que no lo he probado nunca.

Y sí que se puede guardar un proyecto y volverlo a abrir después, si no, una aplicación como esta no tendría mucho sentido.

**Comment by rocknard** [comment]
Bueno, pues gracias.

Cierro el tema, que no hay problemas que arreglar.

Saludos.
