### ISSUE TITLE
Bug con exclamaciónes y interrogantes 

### ISSUE THREAD

**Issue by ThePowerofshadow** [Kaplas80/TranslationFramework2#29]
Hola, solo vengo a notificar un problema.
En los textos donde salen interrogantes o exclamaciones ( ¿ y ¡) En el juego salen con un signo totalmente diferente

¿Sabes cómo podría arreglar esto?

Gracias.

**Comment by Kaplas80** [comment]
Hola. ¿A qué juego te refieres?

**Comment by ThePowerofshadow** [comment]
> Hola. ¿A qué juego te refieres?

Buenas disculpa ahora me doy cuenta de que no he dicho el juego, 

El juego es el yakuza kiwami 


Disculpe las molestias

**Comment by Kaplas80** [comment]
Pues debería ser suficiente con:

1. activar la opción "Usar codificación ISO-8859-1" en el exe
![image](https://user-images.githubusercontent.com/5345429/113598262-2867e100-963d-11eb-9b08-730838bd1512.png)

2. Sustituir la fuente hd2_hankaku.dds (en el `font.par`) por cualquiera de las que están en "Fuentes Yakuza Kiwami.zip"

3. Ajustar el espaciado de caracteres (también en el exe)
![image](https://user-images.githubusercontent.com/5345429/113598330-45041900-963d-11eb-858a-906e2005eb2c.png)

**Comment by ThePowerofshadow** [comment]
> Pues debería ser suficiente con:
> 
> 1. activar la opción "Usar codificación ISO-8859-1" en el exe
> ![image](https://user-images.githubusercontent.com/5345429/113598262-2867e100-963d-11eb-9b08-730838bd1512.png)
> 
> 2. Sustituir la fuente hd2_hankaku.dds (en el `font.par`) por cualquiera de las que están en "Fuentes Yakuza Kiwami.zip"
> 
> 3. Ajustar el espaciado de caracteres (también en el exe)
> ![image](https://user-images.githubusercontent.com/5345429/113598330-45041900-963d-11eb-858a-906e2005eb2c.png)
> 
> 
¡Muchas gracias por la ayuda!

**Comment by ThePowerofshadow** [comment]
Siento mucho volver a molestarte pero
¿Sería tan amable de decirme a cuánto exactamente tengo que ajustar los caracteres del exe? Es que llevo varios días intentando buscar el ajuste que haga que me desaparezca el error de los caracteres y no logro hacerlo por eso ¿Me podría decir a cuánto tendría que poner cada ajuste de los interrogantes y exclamaciónes?

Gracias.

**Comment by Kaplas80** [comment]
Hola!

No te puedo decir exactamente los valores que tienes que poner. Eso depende de la fuente que vayas a usar y tu gusto personal.

Cada carácter tiene 6 valores: 3 son los márgenes en la parte superior, media e inferior por la izquierda y los otros 3 son los márgenes superior, medio e inferior por la derecha.

Cada vez que va a dibujar un carácter, el juego hace un cálculo usando los márgenes derechos del carácter anterior y los izquierdos del carácter que va a dibujar y, a partir de ahí, define la posición en la que dibujarlo.

La aplicación tiene un "previsualizador" para que veas los márgenes dibujados sobre el propio carácter y cómo va a quedar el texto en el juego. No es exactamente igual que el calculo que hace el juego, pero vale como aproximación:

![image](https://user-images.githubusercontent.com/5345429/115152751-be0a6400-a072-11eb-86bc-1375f059bdf6.png)

**Comment by ThePowerofshadow** [comment]
¿Al menos podría saber cuál de las fuentes que hay es la que puede causar menos errores?

**Comment by ThePowerofshadow** [comment]
¿O podrías decirme cuál fuente y ajustes Tienes puestos si no es un problema?

**Comment by Kaplas80** [comment]
Yo no hago las traducciones, así que no sé que ajustes se han puesto ni la fuente que usa. Incluí varias para que se usase la que más gustase a quien use la aplicación.

Y ninguna es exactamente igual a la original así que, en ese sentido, en todas hay que hacer ajustes de anchos.

De todas formas, el botón de autoajustar funciona bastante bien.

**Comment by ThePowerofshadow** [comment]
Gracias
