### ISSUE TITLE
Get error when try unpack street_name in Yakuza  Kiwami with Patch 5

### ISSUE THREAD

**Issue by linkmadao** [Kaplas80/TranslationFramework2#3]
Buscando .\street_name_?.dat...
ERROR: O índice estava fora dos limites da matriz.
   em TF.IO.ExtendedBinaryReader.ReadInt16() na E:\Projetos\Tradução de Jogos\Yakuza Kiwami\TranslationFramework2-master\TranslationFramework2-master\src\TF.IO\ExtendedBinaryReader.cs:linha 65
   em TF.IO.ExtendedBinaryReader.PeekInt16() na E:\Projetos\Tradução de Jogos\Yakuza Kiwami\TranslationFramework2-master\TranslationFramework2-master\src\TF.IO\ExtendedBinaryReader.cs:linha 222
   em YakuzaGame.Files.StreetName.File.GetSubtitles() na E:\Projetos\Tradução de Jogos\Yakuza Kiwami\TranslationFramework2-master\TranslationFramework2-master\src\Plugins\YakuzaGame\Files\StreetName\File.cs:linha 27
   em TF.Core.Files.BinaryTextFile.get_SubtitleCount() na E:\Projetos\Tradução de Jogos\Yakuza Kiwami\TranslationFramework2-master\TranslationFramework2-master\src\TF.Core\Files\BinaryTextFile.cs:linha 28
   em TF.Core.TranslationProject.UpdateTranslationFiles(TranslationProject project, BackgroundWorker worker) na E:\Projetos\Tradução de Jogos\Yakuza Kiwami\TranslationFramework2-master\TranslationFramework2-master\src\TF.Core\TranslationProject.cs:linha 449
   em TF.GUI.MainForm.<>c__DisplayClass4_0.<CreateNewTranslation>b__0(Object sender, DoWorkEventArgs args) na E:\Projetos\Tradução de Jogos\Yakuza Kiwami\TranslationFramework2-master\TranslationFramework2-master\src\TF.GUI\MainForm.Code.cs:linha 79

**Comment by Kaplas80** [comment]
Hi! I've tried to create a new translation project and it works for me:

![Sin título](https://user-images.githubusercontent.com/5345429/63753231-f9ab5580-c8b2-11e9-94db-c3fcd570a3c9.png)

Are you sure you have the latest game update installed (steam build id: 3645748)? If so, please, send me your "street_name" files from "Yakuza Kiwami\media\data\stage\w64\flag_data" so I can do some tests.

**Comment by Kaplas80** [comment]
I can't tell you any forum because, as far as I know, nobody is translating Yakuza Kiwami with my app.

But the app has a built-in search. It will search a text inside all recognised files.

If the app doesn't find the text, you can open an issue here and I'll try to find it.
