### ISSUE TITLE
Soporte para yakuza black panther

### ISSUE THREAD

**Issue by ThePowerofshadow** [Kaplas80/TranslationFramework2#31]
Hola primero de todo debo decirte que Muchas gracias por la ayuda con mi problema con los caracteres del yakuza kiwami 
Esta vez vengo a preguntar si sería posible un soporte para el yakuza black panter de PSP? Estaría interesado en traducirlo para dar un poco más a conocer este juego que desafortunadamente no salió de Japón
Tanto si es posible como no te doy gracias de antemano.

**Comment by Kaplas80** [comment]
Hola!
En principio voy a incluir solo los juegos que han salido para PC. Si, cuando haya incluido todos los de PC, veo que los de consola requieren poca investigación, también los añadiré.
