### ISSUE TITLE
Error "¿ Y ¡"

### ISSUE THREAD

**Issue by HorrorKingMario** [Kaplas80/TranslationFramework2#32]
Buenas! ¿Podrías decirme exactamente como tengo que ajustar los caracteres del yakuza kiwami? porque estoy tienendo errores con " ¿ Y ¡"

**Comment by Kaplas80** [comment]
Hola!

Aquí tienes los pasos: https://github.com/Kaplas80/TranslationFramework2/issues/29#issuecomment-813489930

**Comment by HorrorKingMario** [comment]
Muchas Gracias! A ver si puedo solucionar esto😁
