### ISSUE TITLE
Juegos 

### ISSUE THREAD

**Issue by HorrorKingMario** [Kaplas80/TranslationFramework2#33]
Podrías dar soporte a Doom 2016,Doom Eternal,Mortal Kombat 9,X y 11?

**Comment by Kaplas80** [comment]
Ninguno de esos está en mis planes. Los Yakuza me van a llevar bastante tiempo y, cuando acabe con ellos, ya veré que otros juegos incluyo.

**Comment by HorrorKingMario** [comment]
Entiendo

**Comment by HorrorKingMario** [comment]
Era para ver si podía hacer una mejor traducción

**Comment by HorrorKingMario** [comment]
Era para ver si podía hacer una mejor traducción

**Comment by Kaplas80** [comment]
El investigar los formatos de cualquier juego suele llevar muchísimo tiempo y, a no ser que la traducción oficial esté escandalosamente mal hecha, no merece la pena.
