### ISSUE TITLE
Yakuza Ishin auth folder

### ISSUE THREAD

**Issue by Valacdi** [Kaplas80/TranslationFramework2#34]
The program refuses to scan the auth folder for ishin, and that folder contains subtitles for the cutscenes. Is there a way to make the program read and open the auth folder's .par files? Or is this intentional?

**Comment by Kaplas80** [comment]
Hello!

The support for Ishin is partial and the app only extracts the texts from the files that the "Ishin English Translation group" asked for.

@GarnetSunset made an automatic translation but I don't know if he modified my app or he extracted the texts in auth folder by other way.

**Comment by GarnetSunset** [comment]
something to keep in mind as well is if you're using the ps4 release the folder is /auth_ps4 and needs to be renamed to /auth
