### ISSUE TITLE
Problema con símbolos en español (Yakuza Kiwami)

### ISSUE THREAD

**Issue by MaybeDavey** [Kaplas80/TranslationFramework2#38]
Hola Kaplas!

En estos últimos días he estado en un proyecto de traducción de Yakuza Kiwami 1, y he estado usando tu excelente programa para ello. Llevo ya 5 capítulos traducidos, me estoy tomando en serio esta traducción.

Bueno, vamos al grano: tengo un problema con algunos símbolos como la "í Í" (i latina acentuada. No tengo mucho problema con este, pero genera un pequeño espacio de texto); el símbolo "¿" (Este último aparece como "/"; y por ultimo el "¡" (signo de exclamación al revés), el cual aparece como "°".

Ya activé el parche para la codificación ISO-8895-1, y eso solo solucionó el 90% de los problemas que tuve con anterioridad.

Escuché que Malakito trabajó con tu programa y veo que logró solucionar ese problema. ¿Conoces alguna forma de solucionar esto? Te estaría pero que muy agradecido si me lo pudieras decir.

Gracias.

**Comment by Kaplas80** [comment]
Hola! Me alegro de que te guste la aplicación.

Todo lo que pones en el mensaje se puede hacer con el programa:

1. Los símbolos `¿` y `¡`: En la fuente original no están. En la carpeta de la aplicación metí un zip con varias fuentes distintas que sí los incluyen, para que elijas la que más te guste. Para sustituir la fuente en el juego, tienes que buscar el `font.par` en el árbol de ficheros de la aplicación y sustituir el fichero `hd2_hankaku.dds` por la fuente que quieras. Creo que, con alguno de los últimos cambios que hice, tienes que pasarle un PNG y la aplicación te lo convierte al formato que necesita, así que tendrás que convertir antes tu fuente a PNG.

2. El espacio entre caracteres: Para modificar el espacio entre caracteres, tienes que seleccionar el EXE en la aplicación y pulsar en la pestaña `Fuente`. Ahí te da la opción de modificar cada uno de los 6 valores que especifican el espacio de cada caracter.

Lo más fácil es que pulses el botón "Cargar Fuente Nueva" y elijas la fuente que has usado en el paso anterior y después pulsas en el botón "Auto Ajustar" (eso te dejará un espacio de 2 pixeles entre cada carácter). Si después ves que hay alguna letra en la que no te gusta el espacio que se deja, modificas sus valores manualmente (desde la aplicación puedes ver una vista previa "aproximada" de cómo aparecerá en el juego)

**Comment by MaybeDavey** [comment]
Bueno, eso arregló todo. Muchas gracias Kaplas!
