### ISSUE TITLE
Imágenes no se reemplazan (Kiwami 1)

### ISSUE THREAD

**Issue by MaybeDavey** [Kaplas80/TranslationFramework2#39]
Hola.

Hice algunos edits de la presentación de los nombres del Kiwami 1, me aseguré de que tenían el formato correcto y los importé en el programa con su archivo determinado, pero los cambios no se hicieron y siguen igual en inglés.
¿Será algún problema con el software o quizás estoy reemplazando el archivo en la carpeta incorrecta?
![KW1T](https://user-images.githubusercontent.com/85464600/122089422-bea24b00-cdd4-11eb-9378-a88fdc6c9534.jpg)
![122089158-7c790980-cdd4-11eb-900e-5c1afaff2536](https://user-images.githubusercontent.com/85464600/122089441-c366ff00-cdd4-11eb-8a30-8504b4614d6a.png)

**Comment by linkmadao** [comment]
¿Copiaste el archivo que se exportó a la carpeta del juego?
De lo contrario, el archivo exportado se encuentra en la carpeta del proyecto.

**Comment by Kaplas80** [comment]
Hola!

Puede ser lo que dice linkmadao o puede ser que el juego esté buscando la imagen en otro sitio. Esa imagen está también repetida dentro del `pause_c.par`, así que a lo mejor es de ahí de donde la lee.

**Comment by MaybeDavey** [comment]
Solucionado, ¡gracias a todos!
![breakingbadirony_196961446_3066276410268322_212864664455296288_n](https://user-images.githubusercontent.com/85464600/122256476-1b693880-ce9d-11eb-9f92-2de9263e5bca.jpg)
