### ISSUE TITLE
Font Layout Bug

### ISSUE THREAD

**Issue by linkmadao** [Kaplas80/TranslationFramework2#4]
Original Font:
![](https://cdn.discordapp.com/attachments/616049074252021760/616049298307678239/unknown.png)

Fuentes Yakuza Kiwami:
![](https://cdn.discordapp.com/attachments/559894971201749001/616034540091080711/unknown.png)

With the original font many letters and accents, which are necessary for our language, were strange. When I use any font from the Fuentes Yakuza Kiwami folder, the lyrics are improved, but still.
Could you help me with this?

NOTE: I could not use "Yakuza FontCreator" from "External Tools" folder

**Comment by Kaplas80** [comment]
To fix the character spacing, you have to open the game exe file in my app and go to the "Fuente" tab. 

![showup](https://user-images.githubusercontent.com/5345429/63815351-995cf800-c934-11e9-9cce-0bb789a126c5.png)

Then, you have to click on "Cargar Fuente Nueva" and select the same font you'll use in the game. The last step is click on "Auto Ajustar" to let the app calculate the spaces between characters.

**Comment by Kaplas80** [comment]
You are right, there is a bug with character spacing. I think we'll need another patch on the exe. I'll look into it and let you know when I get it fixed.

**Comment by Kaplas80** [comment]
I've just updated the app. It should work now:

![Sin título](https://user-images.githubusercontent.com/5345429/64134680-ad937000-cde0-11e9-9c09-f1e5b63b5bd2.png)

You have to enable the patch in "Parches" tab of the exe file.

My advise is to start a new project with clean files.

**Comment by linkmadao** [comment]
Work like a charm, thanks man
