### ISSUE TITLE
Yakuza 0 Not reading files

### ISSUE THREAD

**Issue by RandomGuy28** [Kaplas80/TranslationFramework2#40]
I'm trying to port a language from GamePass to the Steam, but the program doesn't read any files other than .dds files.
When I manually replace the file and force load it, it shows up as an empty file. [Here](https://drive.google.com/file/d/1kG2WCkfuQ_5IGrdmpyeaIHptFMpoVSNi/view?usp=sharing)'s some files so you can investigate.
Also, do you know if there is a way to force the language or fonts to load by modifying the exe?
Due to the way the Steam version handles fonts files, replacing the files with the GamePass version doesn't seem to work.
The fonts doesn't load, so I'll have to port everything manually by replacing the English fonts and characters.

**Comment by Kaplas80** [comment]
Hi!

My goal with this app was to be able to translate the Steam version from English to Spanish. I'm ok giving support to other languages if they require only minor changes, but I don't have time to investigate other game files or platforms.

I'm sorry I can't help you with your problem. If replacing files doesn't show any text, it probably means that GamePass file structure is different from Steam one.

The app is open source, so fell free to fork it and make the changes you need.

Regards
