### ISSUE TITLE
yakuza 3 msg

### ISSUE THREAD

**Issue by kroamele1232** [Kaplas80/TranslationFramework2#42]
hello we want to translate yakuza 3 for free but we could not find a tool can this tool be developed or changed for yakuza 3?

**Comment by Kaplas80** [comment]
Hi!

My goal is to make all Yakuza games translatable, but I can't tell when it will be done.

You can see [this comment](https://github.com/Kaplas80/TranslationFramework2/issues/25#issuecomment-789643970)

**Comment by kroamele1232** [comment]
> Hi!
> 
> My goal is to make all Yakuza games translatable, but I can't tell when it will be done.
> 
> You can see [this comment](https://github.com/Kaplas80/TranslationFramework2/issues/25#issuecomment-789643970)

okay thanks
