### ISSUE TITLE
The MISSING: J.J. Macfield buildID mismatch

### ISSUE THREAD

**Issue by fixx1983** [Kaplas80/TranslationFramework2#43]
As the problam says, it requires version of the game with BuildID 3174849, but now the new biuldID is 4168963, with a lot of differences in files

https://steamdb.info/patchnotes/4168963/

**Comment by Kaplas80** [comment]
Have you tried to create a new project using the current app and the latest game build id?

The build id in the app is the version of the game I used in the moment I coded the app, but it doesn't mean that it won't work with other build ids.

If you have tried and it doesn't work, it would be very helpful if you can tell me which files throw an error or aren't translated correctly.

**Comment by Kaplas80** [comment]
Hello again.

I think I've fixed it, but I haven't tested it. Please, try it when you have some time and let me know if it works.

**Comment by fixx1983** [comment]
> Hello again.
> 
> I think I've fixed it, but I haven't tested it. Please, try it when you have some time and let me know if it works.

Sorry but github didn't show me any notification abourt your previous answer, because no Idea. Anyway the program simply gave me a generic long error, maybe about resource.assets.

Will try tomorrow, check if it's fixed an report here.

Thanks so much

**Comment by foubou** [comment]
@Kaplas80 I tested the updated version of TF2 and it worked. I was able to create a new translation project and I was also able to apply my old translations (made with another version of TF2). Thank you for fixing it !

@fixx1983 Thank you for trying too and keep us posted !

**Comment by fixx1983** [comment]
Can confirm it works. So I will close the issue. Thanks Kaplas
