### ISSUE TITLE
Import preview dds crashing

### ISSUE THREAD

**Issue by linkmadao** [Kaplas80/TranslationFramework2#45]
Last version of Translationframework2 crash in Yakuza Kiwami Project when i preview a image dds.

OBS: This is a new project

![image](https://user-images.githubusercontent.com/6817344/135180901-15b58e76-718c-49ea-908f-8cf4bd8747ca.png)

**Comment by Kaplas80** [comment]
I'm testing it and it works fine here.

![image](https://user-images.githubusercontent.com/5345429/135332817-f4660be6-03b7-4128-82de-e43d6ed15b08.png)

A few weeks ago, I updated the DirectXTexNet library version used in the app. Maybe you are using the plugin compiled with the old version?
