### ISSUE TITLE
AITSF - Import all Excel files in TF2 at once

### ISSUE THREAD

**Issue by foubou** [Kaplas80/TranslationFramework2#48]
Is there a way to import all XLS files from a folder in TF2 ?
Need to import +400 files and doing it one by one is a little bit boring.
Thank you for the help !

![TF2 import all](https://user-images.githubusercontent.com/26176310/143438938-05de0f39-a27d-4016-a3a7-fa5896b3b8d8.png)

**Comment by Kaplas80** [comment]
I'm sorry, but I only implemented bulk import and export for PO files and images.

Few weeks ago, other user made [this pull request](https://github.com/Kaplas80/TranslationFramework2/pull/44) to add the functionality, but I asked him to make some changes to merge it with my source code and he never replied.

**Comment by foubou** [comment]
Ok, it wasn't a big deal anyway. Thank you for your reply ! :)
