### ISSUE TITLE
Editing fonts

### ISSUE THREAD

**Issue by AstraeaZero** [Kaplas80/TranslationFramework2#8]
Hello again, i back after pause break, you can explain me how fonts work? actualy i have hd_hankaku.dds, original and moded, in your program i can't load any of this files. All time i see this error:
![image](https://user-images.githubusercontent.com/44085780/71371418-627cb300-25b1-11ea-9194-ed2b66a08991.png)
I clicked "Cargar Fuente Nueva" and selected hd_hankaku.dss

**Comment by AstraeaZero** [comment]
Ok i notice a zip font in your folder, but im stuck here:
![image](https://user-images.githubusercontent.com/44085780/71373409-614e8480-25b7-11ea-9ffe-11a84fe427a5.png)

**Comment by Kaplas80** [comment]
Hi! The DDS format is DXT5, but I don't use Photoshop, so I can't help you with the options. 

For the second question, you can modify [this file](https://github.com/Kaplas80/TranslationFramework2/blob/master/src/Plugins/TFGame.Yakuza0/Encoding.cs) to add the replacements you need in `EncodingReplacements` and then recompile the app.

For example, to change `ć` to `á` you should add this line:
```
new Tuple<string, string>("ć", "á"),
```
This way, you can use ć character in the app, but it will be replaced with á character when it creates the files.
