### ISSUE TITLE
TRAILS IN THE SKY EXECUTABLE TEXTS

### ISSUE THREAD

**Issue by foubou** [Kaplas80/TranslationFramework2#9]
Hi, with the new versions of TranslationFramework, some executable texts such as : SPD UP, AGL UP... have disappeared. Can you please update your tool and restore them? 

![exe texts](https://user-images.githubusercontent.com/26176310/71447827-ebbbf300-2733-11ea-85fa-2f3a53c65bb1.jpg)

**Comment by Kaplas80** [comment]
Hi!

Thank you for the issue, it should be fixed now.

Please, let me know if you find other missing texts.
